// About / how-it-works: the honest version of the privacy story.

import { el } from '../ui.js';

export function render(main) {
  main.append(
    el('div', { class: 'hero' },
      el('h1', {}, 'How Moxy works — and exactly what it does and doesn’t protect'),
      el('p', { class: 'lede' },
        'Moxy is a static page. There is no backend, no database, no analytics, no cookies. ',
        'Everything below is verifiable in the source.'),
    ),

    el('div', { class: 'card' },
      el('h2', {}, '🔗 Your profile is the link'),
      el('p', {},
        'When you finish the survey, your answers are compressed and encoded into the part of the ',
        'URL after the # sign — the “fragment”. Browsers never send the fragment over the ',
        'network, so even the server that hosts this page cannot see your profile. The QR code is ',
        'just that same link, drawn as squares. Sharing your profile means handing someone the ',
        'data itself; deleting every copy of the link deletes the profile.'),
      el('p', { class: 'sub' },
        'Corollary: anyone you give the link to can see the open answers and can pass the link ',
        'on. Treat it like a business card, not a secret.'),
    ),

    el('div', { class: 'card' },
      el('h2', {}, '🎭 The desires section: mutual reveal, honestly explained'),
      el('p', {},
        'Desires never travel as readable answers. Each positive answer (anything warmer than ',
        '“Not for me”) is turned into a scrambled fingerprint — a salted hash. When two profiles ',
        'are compared, the page checks whether both carry a fingerprint for the same desire, and ',
        'only then reveals it. One-sided interests stay invisible, and the fingerprints are ',
        'padded and shuffled so even the number of desires you marked isn’t exposed.'),
      el('div', { class: 'notice-warn notice' },
        el('strong', {}, 'The honest limit: '),
        'because there’s no server to referee, a technically skilled person with your link could ',
        'test every possible desire against the fingerprints and recover your positive answers. ',
        '“Not for me” answers are never encoded in any form, so they are genuinely unknowable. ',
        'Rule of thumb: mark a desire only if you’d be comfortable with an enthusiastic match ',
        'knowing it — the curtain is real, but it’s a curtain, not a wall.'),
    ),

    el('div', { class: 'card' },
      el('h2', {}, '🔑 The vault: an account with no identity'),
      el('p', {},
        'The vault gives you “log back in and edit” without an account. We generate a five-word ',
        'passphrase (from a 7,776-word list — about 65 bits of entropy). Your passphrase is run ',
        'through PBKDF2 (300,000 rounds of SHA-512) to derive two things: a locator that names ',
        'your vault in this browser’s storage, and an AES-256-GCM key that encrypts it. The ',
        'passphrase itself is never stored — not hashed, not anywhere.'),
      el('ul', {},
        el('li', {}, 'Keep the passphrase → you can unlock, edit, and re-share.'),
        el('li', {}, 'Lose it → the vault is unrecoverable ciphertext. Nobody can help, and that’s the point.'),
        el('li', {}, 'Your share link and your passphrase are unrelated — a link can never unlock a vault, and read access never grants edit access.'),
        el('li', {}, 'Vaults are stored per-browser. Export the encrypted file to move or back it up.'),
      ),
    ),

    el('div', { class: 'card' },
      el('h2', {}, '🧭 Who Moxy is for'),
      el('p', {},
        'Everyone whose connections don’t fit one template: monogamous couples checking ',
        'alignment before moving in; polycules mapping a constellation; swingers and play ',
        'partners negotiating interests without awkward guessing; asexual and aromantic folks ',
        'looking for queerplatonic partnership; friends who want to know if they’d survive a ',
        'road trip. The survey treats every one of those as a first-class outcome, not a niche.'),
    ),

    el('div', { class: 'card' },
      el('h2', {}, '🛠️ Verify or self-host it'),
      el('p', {},
        'Moxy is open source (MIT) and intentionally boring to host: static files, no build ',
        'step. Clone the repository and open index.html, or drop the folder onto any static ',
        'host (GitHub Pages works). Because profiles live in the links, profiles made on one ',
        'copy of Moxy open fine on any other copy — append your fragment to any Moxy URL.'),
      el('p', { class: 'sub' },
        'Threat-model fine print: Moxy can’t protect you from what you choose to share, from ',
        'someone photographing your screen, or from a compromised device or browser ',
        'extension. It simply refuses to create the databases such attacks usually target.'),
    ),
  );
}
