import { el } from '../ui.js';

export function render(main) {
  main.append(
    el('section', { class: 'hero' },
      el('span', { class: 'brand-mark', 'aria-hidden': 'true', text: 'M' }),
      el('h1', {}, 'Know where you overlap — without giving up who you are.'),
      el('p', { class: 'lede' },
        'Moxy is a compatibility survey for every kind of connection — friendship, partnership, ',
        'polyamory, marriage, play partners, chosen family. Your answers become a link you can ',
        'share; lay two or more profiles side by side and see the overlap, the gaps, and the ',
        'possibilities. No accounts. No servers. Nothing to trace back to you.'),
    ),
    el('div', { class: 'home-cards' },
      el('div', { class: 'card home-card' },
        el('h2', {}, '📝 Make your profile'),
        el('p', { class: 'sub' },
          'A thoughtful survey about who you are, what you value, and what kinds of connection ',
          'you’re open to. Every question is optional.'),
        el('a', { class: 'btn btn-primary', href: '#/survey' }, 'Start the survey'),
      ),
      el('div', { class: 'card home-card' },
        el('h2', {}, '🔍 Compare profiles'),
        el('p', { class: 'sub' },
          'Paste profile links side by side. See value alignment, mutual interests, lifestyle ',
          'fits and gaps — and private desires only where they’re mutual.'),
        el('a', { class: 'btn', href: '#/compare' }, 'Open the compare view'),
      ),
      el('div', { class: 'card home-card' },
        el('h2', {}, '🔑 Your vault'),
        el('p', { class: 'sub' },
          'Save profiles and connections behind a passphrase — generated for you, stored by no ',
          'one. Keep it and you can come back; lose it and it’s gone. That’s the deal.'),
        el('a', { class: 'btn', href: '#/vault' }, 'Open the vault'),
      ),
    ),
    el('div', { class: 'card' },
      el('div', { class: 'privacy-strip' },
        el('div', {},
          el('h3', {}, '🔗 The link is the database'),
          el('p', { class: 'sub' },
            'Your profile is compressed into the link itself (the part after #, which browsers ',
            'never send to any server). Delete the link, and the profile no longer exists.')),
        el('div', {},
          el('h3', {}, '🎭 Mutual-only reveals'),
          el('p', { class: 'sub' },
            'The optional desires section is shared only as scrambled fingerprints. A desire ',
            'is revealed only when both profiles marked it — and "not for me" answers are ',
            'never shared in any form.')),
        el('div', {},
          el('h3', {}, '🕳️ Nothing identifies you'),
          el('p', { class: 'sub' },
            'No email, no phone number, no login. A random passphrase is your only key, and ',
            'it never leaves your device.')),
      ),
    ),
  );
}
