// Persona wordlists and colors.
//
// COMPATIBILITY CONTRACT: every index that has shipped is FROZEN — a persona
// derives deterministically from a seed carried in share links, so reordering,
// removing, or replacing an entry would silently rename everyone's creature.
// Fixing a typo in place is the only acceptable edit, and only if the word
// stays recognizably the same.
//
// APPENDING IS SAFE, and is how these lists grow. Nothing indexes into them to
// validate or derive: `isViewPhraseShaped` tests membership (.includes/Set.has)
// and `personaFromViewPhrase` hashes the literal phrase string. A longer list
// therefore widens the mint space without touching a single existing phrase —
// proven by the vectors in hatch/phrase-compat.spec.ts.
//
// Grown 64 → 128 (ANIMALS → 108 with emoji, then onward by name; see the
// note on that list and docs/animal-plan.md). Every table that
// is index-ALIGNED with one of these must grow in the same commit: ADJ_B_HUES
// (adjb-hues.ts) with ADJECTIVES_B, ANIMAL_HABITATS (habitat.ts) with ANIMALS.
// The lockstep is asserted by length-equality tests, not by magic numbers.

/** 128 entries — first adjective slot. Disjoint from ADJECTIVES_B. */
export const ADJECTIVES_A: readonly string[] = [
  'amber',
  'brave',
  'calm',
  'clever',
  'cosmic',
  'crisp',
  'daring',
  'deft',
  'dusky',
  'eager',
  'fabled',
  'fierce',
  'gentle',
  'gilded',
  'golden',
  'happy',
  'hardy',
  'hidden',
  'humble',
  'jolly',
  'keen',
  'kind',
  'lively',
  'loyal',
  'lucid',
  'lunar',
  'mellow',
  'merry',
  'mighty',
  'misty',
  'noble',
  'nimble',
  'opal',
  'plucky',
  'proud',
  'quiet',
  'quick',
  'radiant',
  'rustic',
  'sable',
  'sage',
  'sandy',
  'silent',
  'silver',
  'sleek',
  'solar',
  'spry',
  'stellar',
  'stoic',
  'sunny',
  'swift',
  'tidal',
  'tranquil',
  'true',
  'velvet',
  'vivid',
  'wandering',
  'warm',
  'wild',
  'winter',
  'witty',
  'zealous',
  'zesty',
  'bold',
  // --- appended (64 → 128) ---
  'adept',
  'agile',
  'airy',
  'ancient',
  'ardent',
  'artful',
  'bashful',
  'blithe',
  'boundless',
  'buoyant',
  'canny',
  'careful',
  'chipper',
  'civil',
  'clement',
  'cordial',
  'courtly',
  'crafty',
  'dauntless',
  'dazzling',
  'devoted',
  'diligent',
  'dogged',
  'doughty',
  'dulcet',
  'earnest',
  'easy',
  'elegant',
  'endless',
  'fearless',
  'fleet',
  'fond',
  'free',
  'frisky',
  'gallant',
  'genial',
  'gladsome',
  'grand',
  'hallowed',
  'hearty',
  'heedful',
  'honest',
  'hopeful',
  'intrepid',
  'jovial',
  'joyous',
  'jubilant',
  'lanky',
  'limpid',
  'lofty',
  'lucky',
  'mirthful',
  'modest',
  'nifty',
  'nomadic',
  'patient',
  'peerless',
  'pensive',
  'placid',
  'prime',
  'pristine',
  'prudent',
  'rapid',
  'restless',
];

/**
 * 128 entries — second adjective slot (distinct list: no "brave-brave").
 * Every entry is color-adjacent, because each needs an index-aligned hue in
 * ADJ_B_HUES; light-sounding words (ivory, seafoam) still get a dark hue "in
 * their spirit", exactly as `snowy` already does.
 */
export const ADJECTIVES_B: readonly string[] = [
  'azure',
  'blazing',
  'breezy',
  'bright',
  'bubbly',
  'candid',
  'cheerful',
  'chill',
  'coral',
  'cozy',
  'crimson',
  'curious',
  'dapper',
  'dreamy',
  'electric',
  'emerald',
  'feathered',
  'festive',
  'floral',
  'frosty',
  'fuzzy',
  'glowing',
  'graceful',
  'groovy',
  'honeyed',
  'indigo',
  'jade',
  'jaunty',
  'lavender',
  'lemony',
  'limber',
  'maroon',
  'mango',
  'marble',
  'midnight',
  'minty',
  'mossy',
  'ochre',
  'olive',
  'onyx',
  'peachy',
  'pearly',
  'peppy',
  'perky',
  'plum',
  'prancing',
  'rosy',
  'ruby',
  'saffron',
  'sapphire',
  'scarlet',
  'snappy',
  'snowy',
  'sparkling',
  'spiffy',
  'spotted',
  'starry',
  'striped',
  'tangy',
  'twilight',
  'umber',
  'verdant',
  'violet',
  'wavy',
  // --- appended (64 → 128) ---
  'alabaster',
  'almond',
  'amethyst',
  'apricot',
  'aquamarine',
  'auburn',
  'basalt',
  'beryl',
  'bistre',
  'bronze',
  'burgundy',
  'cerulean',
  'chartreuse',
  'cherry',
  'chocolate',
  'cinnabar',
  'citrine',
  'clay',
  'cobalt',
  'copper',
  'cornflower',
  'cranberry',
  'damson',
  'denim',
  'ebony',
  'flaxen',
  'garnet',
  'ginger',
  'glacial',
  'gunmetal',
  'hazelnut',
  'heliotrope',
  'iris',
  'ivory',
  'kelp',
  'lapis',
  'lilac',
  'magenta',
  'mahogany',
  'malachite',
  'mauve',
  'mulberry',
  'mustard',
  'nutmeg',
  'obsidian',
  'oxblood',
  'paprika',
  'periwinkle',
  'pewter',
  'pistachio',
  'porphyry',
  'quartz',
  'russet',
  'seafoam',
  'sepia',
  'sienna',
  'slate',
  'spruce',
  'tawny',
  'teal',
  'terracotta',
  'topaz',
  'turquoise',
  'vermilion',
];

export interface AnimalEntry {
  readonly name: string;
  /**
   * OPTIONAL, and no longer the identity. Art is keyed by `name` (see
   * creatures/pixel-grids.ts), which is what let this list grow past the
   * point where distinct single-codepoint animal emoji ran out. Where an
   * emoji exists it is still the fallback glyph and still travels in boops,
   * so entries that have one keep it and it stays unique among them.
   */
  readonly emoji?: string;
}

/**
 * The first 108 entries each carry a single-codepoint emoji (no VS16
 * sequences, and no default-text-presentation codepoints like U+1F54A DOVE,
 * which render as a monochrome glyph without VS16). Asserted in
 * persona.spec.ts — for the entries that have one.
 *
 * The list stopped at 108 because that supply is genuinely exhausted: a scan
 * of the creature codepoint ranges turns up only a handful of usable glyphs
 * left, and the rest are near-duplicates (a second cat, a second baby chick)
 * that would buy fractions of a bit at the cost of a creature you can't tell
 * from another. Growth past 108 therefore carries no emoji and is identified
 * by NAME, with a hand-drawn sprite that a spec requires. See
 * docs/animal-plan.md and docs/pixel-art-guide.md.
 */
export const ANIMALS: readonly AnimalEntry[] = [
  { name: 'fox', emoji: '🦊' },
  { name: 'otter', emoji: '🦦' },
  { name: 'owl', emoji: '🦉' },
  { name: 'wolf', emoji: '🐺' },
  { name: 'bear', emoji: '🐻' },
  { name: 'panda', emoji: '🐼' },
  { name: 'koala', emoji: '🐨' },
  { name: 'tiger', emoji: '🐯' },
  { name: 'lion', emoji: '🦁' },
  { name: 'cat', emoji: '🐱' },
  { name: 'dog', emoji: '🐶' },
  { name: 'rabbit', emoji: '🐰' },
  { name: 'hamster', emoji: '🐹' },
  { name: 'mouse', emoji: '🐭' },
  { name: 'hedgehog', emoji: '🦔' },
  { name: 'bat', emoji: '🦇' },
  { name: 'frog', emoji: '🐸' },
  { name: 'turtle', emoji: '🐢' },
  { name: 'gecko', emoji: '🦎' },
  { name: 'octopus', emoji: '🐙' },
  { name: 'squid', emoji: '🦑' },
  { name: 'shrimp', emoji: '🦐' },
  { name: 'crab', emoji: '🦀' },
  { name: 'lobster', emoji: '🦞' },
  { name: 'pufferfish', emoji: '🐡' },
  { name: 'fish', emoji: '🐠' },
  { name: 'dolphin', emoji: '🐬' },
  { name: 'whale', emoji: '🐳' },
  { name: 'shark', emoji: '🦈' },
  { name: 'seal', emoji: '🦭' },
  { name: 'penguin', emoji: '🐧' },
  { name: 'duck', emoji: '🦆' },
  { name: 'swan', emoji: '🦢' },
  { name: 'eagle', emoji: '🦅' },
  { name: 'parrot', emoji: '🦜' },
  { name: 'flamingo', emoji: '🦩' },
  { name: 'peacock', emoji: '🦚' },
  { name: 'rooster', emoji: '🐓' },
  { name: 'chick', emoji: '🐤' },
  { name: 'butterfly', emoji: '🦋' },
  { name: 'bee', emoji: '🐝' },
  { name: 'ladybug', emoji: '🐞' },
  { name: 'snail', emoji: '🐌' },
  { name: 'unicorn', emoji: '🦄' },
  { name: 'dragon', emoji: '🐉' },
  { name: 'horse', emoji: '🐴' },
  { name: 'zebra', emoji: '🦓' },
  { name: 'deer', emoji: '🦌' },
  { name: 'giraffe', emoji: '🦒' },
  { name: 'elephant', emoji: '🐘' },
  { name: 'rhino', emoji: '🦏' },
  { name: 'hippo', emoji: '🦛' },
  { name: 'camel', emoji: '🐪' },
  { name: 'llama', emoji: '🦙' },
  { name: 'sloth', emoji: '🦥' },
  { name: 'kangaroo', emoji: '🦘' },
  { name: 'badger', emoji: '🦡' },
  { name: 'beaver', emoji: '🦫' },
  { name: 'skunk', emoji: '🦨' },
  { name: 'raccoon', emoji: '🦝' },
  { name: 'monkey', emoji: '🐵' },
  { name: 'gorilla', emoji: '🦍' },
  { name: 'goat', emoji: '🐐' },
  { name: 'sheep', emoji: '🐑' },
  // --- appended (64 → 108) ---
  { name: 'orangutan', emoji: '🦧' },
  { name: 'mammoth', emoji: '🦣' },
  { name: 'bison', emoji: '🦬' },
  { name: 'dodo', emoji: '🦤' },
  { name: 'crocodile', emoji: '🐊' },
  { name: 'snake', emoji: '🐍' },
  { name: 'scorpion', emoji: '🦂' },
  { name: 'ant', emoji: '🐜' },
  { name: 'beetle', emoji: '🪲' },
  { name: 'caterpillar', emoji: '🐛' },
  { name: 'cricket', emoji: '🦗' },
  { name: 'worm', emoji: '🪱' },
  { name: 'turkey', emoji: '🦃' },
  { name: 'songbird', emoji: '🐦' },
  { name: 'hatchling', emoji: '🐣' },
  { name: 'chicken', emoji: '🐔' },
  { name: 'pig', emoji: '🐖' },
  { name: 'boar', emoji: '🐗' },
  { name: 'cow', emoji: '🐄' },
  { name: 'ox', emoji: '🐂' },
  { name: 'buffalo', emoji: '🐃' },
  { name: 'stallion', emoji: '🐎' },
  { name: 'ram', emoji: '🐏' },
  { name: 'hound', emoji: '🐕' },
  { name: 'retriever', emoji: '🦮' },
  { name: 'poodle', emoji: '🐩' },
  { name: 'tabby', emoji: '🐈' },
  { name: 'leopard', emoji: '🐆' },
  { name: 'jaguar', emoji: '🐅' },
  { name: 'macaque', emoji: '🐒' },
  { name: 'bactrian', emoji: '🐫' },
  { name: 'sauropod', emoji: '🦕' },
  { name: 'raptor', emoji: '🦖' },
  { name: 'wyvern', emoji: '🐲' },
  { name: 'vole', emoji: '🐁' },
  { name: 'rat', emoji: '🐀' },
  { name: 'hare', emoji: '🐇' },
  { name: 'humpback', emoji: '🐋' },
  { name: 'minnow', emoji: '🐟' },
  { name: 'jellyfish', emoji: '🪼' },
  { name: 'goose', emoji: '🪿' },
  { name: 'moose', emoji: '🫎' },
  { name: 'donkey', emoji: '🫏' },
  { name: 'nautilus', emoji: '🐚' },

  // --- batch 1 (no emoji: the supply ran out at 108; identified by name) ---
  { name: 'lynx' },
  { name: 'caracal' },
  { name: 'ocelot' },
  { name: 'puma' },
  { name: 'cheetah' },
  { name: 'coyote' },
  { name: 'dingo' },
  { name: 'fennec' },
  { name: 'hyena' },
  { name: 'marten' },
  { name: 'wolverine' },
  { name: 'ferret' },
  { name: 'mongoose' },
  { name: 'meerkat' },
  { name: 'coati' },
  { name: 'kinkajou' },
  { name: 'ringtail' },
  { name: 'fossa' },
  { name: 'binturong' },

  // --- batch 2 ---
  { name: 'chipmunk' },
  { name: 'marmot' },
  { name: 'gopher' },
  { name: 'mole' },
  { name: 'jerboa' },
  { name: 'chinchilla' },
  { name: 'porcupine' },
  { name: 'capybara' },
  { name: 'pika' },
  { name: 'agouti' },
  { name: 'hyrax' },
  { name: 'pangolin' },
  { name: 'armadillo' },
  { name: 'anteater' },
  { name: 'aardvark' },
  { name: 'echidna' },
  { name: 'platypus' },
  { name: 'wombat' },
  { name: 'quokka' },

  // --- batch 3 ---
  { name: 'gazelle' },
  { name: 'kudu' },
  { name: 'oryx' },
  { name: 'ibex' },
  { name: 'yak' },
  { name: 'markhor' },
  { name: 'saiga' },
  { name: 'springbok' },
  { name: 'tapir' },
  { name: 'okapi' },
  { name: 'wallaby' },
  { name: 'lemur' },
  { name: 'gibbon' },
  { name: 'tarsier' },
  { name: 'mandrill' },
  { name: 'chimp' },
  { name: 'tamarin' },
  { name: 'galago' },
  { name: 'colobus' },
  { name: 'sifaka' },
  { name: 'indri' },

  // --- batch 4 ---
  { name: 'walrus' },
  { name: 'narwhal' },
  { name: 'orca' },
  { name: 'beluga' },
  { name: 'manatee' },
  { name: 'sealion' },
  { name: 'trout' },
  { name: 'salmon' },
  { name: 'koi' },
  { name: 'pike' },
  { name: 'eel' },
  { name: 'marlin' },
  { name: 'tuna' },
  { name: 'seahorse' },
  { name: 'stingray' },
  { name: 'betta' },
  { name: 'discus' },
  { name: 'wrasse' },
  { name: 'lionfish' },
  { name: 'sailfish' },
  { name: 'manta' },
  { name: 'seadragon' },
  { name: 'sunfish' },
  { name: 'starfish' },
  { name: 'anemone' },
  { name: 'cuttlefish' },

  // --- batch 5 ---
  { name: 'heron' },
  { name: 'pelican' },
  { name: 'puffin' },
  { name: 'kingfisher' },
  { name: 'cormorant' },
  { name: 'ibis' },
  { name: 'tern' },
  { name: 'stork' },
  { name: 'dipper' },
  { name: 'avocet' },
  { name: 'plover' },
  { name: 'sandpiper' },
  { name: 'curlew' },
  { name: 'falcon' },
  { name: 'osprey' },
  { name: 'kestrel' },
  { name: 'harrier' },
  { name: 'goshawk' },
  { name: 'condor' },
  { name: 'caracara' },
  { name: 'pheasant' },
  { name: 'ostrich' },
  { name: 'quail' },
  { name: 'kiwi' },

  // --- batch 6 ---
  { name: 'robin' },
  { name: 'sparrow' },
  { name: 'nightingale' },
  { name: 'canary' },
  { name: 'tanager' },
  { name: 'lovebird' },
  { name: 'bluebird' },
  { name: 'parakeet' },
  { name: 'raven' },
  { name: 'magpie' },
  { name: 'goldfinch' },
  { name: 'oriole' },
  { name: 'shrike' },
  { name: 'swallow' },
  { name: 'starling' },
  { name: 'wren' },
  { name: 'finch' },
  { name: 'lark' },
  { name: 'quetzal' },
  { name: 'lorikeet' },
  { name: 'budgie' },
  { name: 'kookaburra' },
  { name: 'hornbill' },
  { name: 'macaw' },
  { name: 'sunbird' },
  { name: 'honeyeater' },
  { name: 'jay' },
  { name: 'cockatiel' },
  { name: 'hoopoe' },
];

/**
 * 16 deep hues, precomputed dark for QR scanability: every entry must keep
 * WCAG relative luminance ≤ 0.20 (asserted in persona.spec.ts), i.e. contrast
 * against white ≥ 4.2:1.
 */
export const PERSONA_COLORS: readonly string[] = [
  '#8b2f5c', // berry
  '#2f6b4f', // pine
  '#1c5cab', // cobalt
  '#8a4b16', // amber
  '#5b3aa7', // violet
  '#a03535', // brick
  '#0f766e', // teal
  '#756215', // olive
  '#9c3d00', // burnt orange
  '#386641', // moss
  '#7b2d8b', // plum
  '#0b5e8a', // ocean
  '#99424f', // rosewood
  '#4a5568', // slate
  '#1d3557', // navy
  '#6d597a', // mauve
];
