// The pixel menagerie: one hand-authored 16×16 sprite per animal in the
// frozen ANIMALS list. First-party art (AGPL like everything else here) —
// no vendored icon set, no attribution baggage, and every creature can be
// touched up as a tiny grid diff. Keys are animal names; a missing key
// simply falls back to the platform emoji, so partial edits are always
// safe. NOT frozen: this is presentation, not identity.
//
// Format: 16 rows of 16 letters. '.' is transparent; every other letter is
// looked up in the sprite's palette. Conventions: o outline, k ink/pupil,
// w white, a primary fill, b secondary (cheeks/muzzle/markings), c accent,
// m dark marking, p pink, y beak/horn.

export interface PixelSprite {
  readonly palette: Readonly<Record<string, string>>;
  readonly rows: readonly string[];
}

// Shared paint pots — sprites mix and match.
const OUT = '#3a2c28'; // warm outline
const INK = '#26262b';
const WHT = '#ffffff';
const CRM = '#f7e8cf';
const RST = '#e8823f';
const GRY = '#a7adb6';
const GRL = '#d7dbe0';
const GRD = '#717986';
const BRN = '#a97a4e';
const BRD = '#7c5330';
const TAN = '#d9b380';
const YLW = '#f2c94c';
const GLD = '#d9a125';
const ORG = '#e8963f';
const GRN = '#7bc06a';
const GND = '#4e8f42';
const LIM = '#a8d060';
const BLU = '#5aa7d6';
const BLD = '#2f6f9e';
const PNK = '#f2a3bd';
const PKD = '#e0709d';
const PRP = '#9b7ed9';
const RED = '#d8514a';
const TEA = '#4fb3a5';
const BLK = '#3d3d44';
const SND = '#e3cfa4';

const EMPTY = '................';
const CHIN = '..oooooooooooo..';

// Pointy-ear muzzle-and-cheeks head shared by the canids. Letter 'b' is the
// cheek/muzzle patch so the palette decides its color per animal.
const CANINE: readonly string[] = [
  EMPTY,
  '.oo..........oo.',
  '.oao........oao.',
  '.oaao......oaao.',
  '.oaaao....oaaao.',
  '.oaaaooooooaaao.',
  '.oaaaaaaaaaaaao.',
  '.oakkaaaaaakkao.',
  '.oakwaaaaaakwao.',
  '.oaaaaaaaaaaaao.',
  '.oabbbaaaabbbao.',
  '.oabbbakkabbbao.',
  '.oabbbbbbbbbbao.',
  CHIN,
  EMPTY,
  EMPTY,
];

// Round-ear head shared by the bears. Letter 'b' is the center muzzle.
const ROUND: readonly string[] = [
  EMPTY,
  '..oo........oo..',
  '.oaao......oaao.',
  '.oaaooooooooaao.',
  '.oaaaaaaaaaaaao.',
  '.oaaaaaaaaaaaao.',
  '.oaaaaaaaaaaaao.',
  '.oakkaaaaaakkao.',
  '.oakwaaaaaakwao.',
  '.oaaaaaaaaaaaao.',
  '.oaaabbbbbbaaao.',
  '.oaaabbkkbbaaao.',
  '.oaaabbbbbbaaao.',
  CHIN,
  EMPTY,
  EMPTY,
];

// Tall narrow face shared by the hoofed crowd. Letter 'b' is the muzzle.
const LONGFACE: readonly string[] = [
  '...oo......oo...',
  '..oaao....oaao..',
  '..oaaooooooaao..',
  '..oaaaaaaaaaao..',
  '..oaaaaaaaaaao..',
  '..oakkaaaakkao..',
  '..oakwaaaakwao..',
  '..oaaaaaaaaaao..',
  '..oaaaaaaaaaao..',
  '..oabbbbbbbbao..',
  '..oabkbbbbkbao..',
  '..oabbbbbbbbao..',
  '...oooooooooo...',
  EMPTY,
  EMPTY,
  EMPTY,
];

export const CREATURE_SPRITES: Readonly<Record<string, PixelSprite>> = {
  // ------------------------------------------------------------- canids &c
  fox: { palette: { o: OUT, a: RST, b: WHT, k: INK, w: WHT }, rows: CANINE },
  wolf: { palette: { o: OUT, a: GRY, b: GRL, k: INK, w: WHT }, rows: CANINE },
  owl: {
    palette: { o: OUT, a: BRN, b: TAN, y: GLD, k: INK, w: WHT },
    rows: [
      '.oo..........oo.',
      '.oao........oao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oawwwwaawwwwao.',
      '.oawkkwaawkkwao.',
      '.oawwwwaawwwwao.',
      '.oaawwayyawwaao.',
      '.oaaaaayyaaaaao.',
      '.oabbaabbaabbao.',
      '.oabbaabbaabbao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  dog: {
    palette: { o: OUT, a: BRN, b: TAN, k: INK, w: WHT },
    rows: [
      EMPTY,
      '..oooooooooooo..',
      '.ooaaaaaaaaaaoo.',
      '.obooaaaaaaoobo.',
      '.oboaaaaaaaaobo.',
      '.oboakkaakkaobo.',
      '.oboakwaakwaobo.',
      '.oooaaaaaaaaooo.',
      '.oaaabbbbbbaaao.',
      '.oaaabbkkbbaaao.',
      '.oaaabbbbbbaaao.',
      '.oaaabbbbbbaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  cat: {
    palette: { o: OUT, a: SND, b: CRM, k: INK, w: WHT, p: PNK },
    rows: [
      EMPTY,
      '.oo..........oo.',
      '.opo........opo.',
      '.oapo......opao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oaabbaaaabbaao.',
      '.oaabbappabbaao.',
      '.oaabbbbbbbbaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  tiger: {
    palette: { o: OUT, a: ORG, b: WHT, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '.oo..........oo.',
      '.oao........oao.',
      '.oaao......oaao.',
      '.oaaao....oaaao.',
      '.oaaaooooooaaao.',
      '.oamaamaamaamao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oabbbaaaabbbao.',
      '.oabbbakkabbbao.',
      '.oabbbbbbbbbbao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  lion: {
    palette: { o: OUT, a: GLD, b: BRD, c: TAN, k: INK, w: WHT },
    rows: [
      '..oooooooooooo..',
      '.obbbbbbbbbbbbo.',
      '.obboooooooobbo.',
      '.oboaaaaaaaaobo.',
      '.oboaaaaaaaaobo.',
      '.obakkaaaakkabo.',
      '.obakwaaaakwabo.',
      '.obaaaaaaaaaabo.',
      '.obaaccccccaabo.',
      '.obaacckkccaabo.',
      '.obaaccccccaabo.',
      '.obbaaaaaaaabbo.',
      '.obbbbbbbbbbbbo.',
      '..oooooooooooo..',
      EMPTY,
      EMPTY,
    ],
  },
  raccoon: {
    palette: { o: OUT, a: GRY, b: WHT, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '.oo..........oo.',
      '.oao........oao.',
      '.oaao......oaao.',
      '.oaaao....oaaao.',
      '.oaaaooooooaaao.',
      '.oaaaaaaaaaaaao.',
      '.omkkmaaaamkkmo.',
      '.omkwmaaaamkwmo.',
      '.oaaaaaaaaaaaao.',
      '.oabbbaaaabbbao.',
      '.oabbbakkabbbao.',
      '.oabbbbbbbbbbao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  skunk: {
    palette: { o: OUT, a: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '.oo...wwww...oo.',
      '.oao..wwww..oao.',
      '.oaao.wwww.oaao.',
      '.oaaaowwwwoaaao.',
      '.oaaaowwwwoaaao.',
      '.oaaawwwwwwaaao.',
      '.oakkawwwwakkao.',
      '.oakwawwwwakwao.',
      '.oaaaawwwwaaaao.',
      '.oaaaawwwwaaaao.',
      '.oaaaaakkaaaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  badger: {
    palette: { o: OUT, a: WHT, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '.oo..........oo.',
      '.omo........omo.',
      '.omao......oamo.',
      '.oaaao....oaaao.',
      '.oaaaooooooaaao.',
      '.oaammaaaammaao.',
      '.oaakmaaaamkaao.',
      '.oaammaaaammaao.',
      '.oaammaaaammaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaakkaaaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  // ---------------------------------------------------------------- bears
  bear: { palette: { o: OUT, a: BRN, b: TAN, k: INK, w: WHT }, rows: ROUND },
  panda: {
    palette: { o: OUT, a: WHT, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '..oo........oo..',
      '.ommo......ommo.',
      '.ommoooooooommo.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oammmaaaammmao.',
      '.oamkmaaaamkmao.',
      '.oamkmaaaamkmao.',
      '.oammmaaaammmao.',
      '.oaaaaakkaaaaao.',
      '.oaaaakaakaaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  koala: {
    palette: { o: OUT, a: GRY, b: GRL, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '.ooo........ooo.',
      'oabao......oabao',
      'oabbo......obbao',
      'oabbooooooooabao',
      '.ooaaaaaaaaaaoo.',
      '..oaaaaaaaaaao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oaaammmmaaao..',
      '..oaaammmmaaao..',
      '..oaaaammaaaao..',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  sloth: {
    palette: { o: OUT, a: TAN, b: BRD, c: CRM, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '...oooooooooo...',
      '..oaaaaaaaaaao..',
      '.oaaaaaaaaaaaao.',
      '.oabbkaaaakbbao.',
      '.oabbkwaawkbbao.',
      '.oaabbaaaabbaao.',
      '.oaaaccccccaaao.',
      '.oaaacckkccaaao.',
      '.oaaaccccccaaao.',
      '.oaaaaaaaaaaaao.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  // ----------------------------------------------------- small & spiky &c
  hedgehog: {
    palette: { o: OUT, a: CRM, m: BRD, k: INK, w: WHT },
    rows: [
      '...o..o..o..o...',
      '..omoomoomoomo..',
      '.ommmmmmmmmmmmo.',
      '.ommmmmmmmmmmmo.',
      '.ommaaaaaaaammo.',
      '.omaaaaaaaaaamo.',
      '.omakkaaaakkamo.',
      '.omakwaaaakwamo.',
      '.omaaaaaaaaaamo.',
      '.omaaaakkaaaamo.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  bat: {
    palette: { o: OUT, a: GRD, b: PRP, k: INK, w: WHT },
    rows: [
      '.o............o.',
      '.oo..........oo.',
      '.obo........obo.',
      '.obbo......obbo.',
      '.obbao....oabbo.',
      '.oaaaooooooaaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaakkaaaaao.',
      '.oaaawaaaawaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  rabbit: {
    palette: { o: OUT, a: CRM, p: PNK, k: INK, w: WHT },
    rows: [
      '..oo........oo..',
      '.oapo......opao.',
      '.oapo......opao.',
      '.oapo......opao.',
      '.oaao......oaao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaappaaaaao.',
      '.oaaawwwwwwaaao.',
      '.oaaaawwwwaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  hamster: {
    palette: { o: OUT, a: TAN, b: CRM, k: INK, w: WHT },
    rows: [
      EMPTY,
      '..oo........oo..',
      '.oabo......obao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.obbaaaaaaaabbo.',
      '.obbbaakkaabbbo.',
      '.obbwwwwwwwwbbo.',
      '.obwwwwwwwwwwbo.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  mouse: {
    palette: { o: OUT, a: GRY, p: PNK, k: INK, w: WHT },
    rows: [
      '..ooo......ooo..',
      '.oaaao....oaaao.',
      '.oappao..oappao.',
      '.oappao..oappao.',
      '.ooaaoooooaaoo..',
      '..oaaaaaaaaaao..',
      '..oaaaaaaaaaao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oaaaaaaaaaao..',
      '..oaaaappaaaao..',
      '..oaaawwwwaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  deer: {
    palette: { o: OUT, a: BRN, b: CRM, m: BRD, k: INK, w: WHT },
    rows: [
      '.omo........omo.',
      '.omoo......oomo.',
      '..omo......omo..',
      '.oaoom....mooao.',
      '.oaaoo....ooaao.',
      '.oaaaooooooaaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oaabbbbbbbbaao.',
      '.oaabbbkkbbbaao.',
      '.oaabbbbbbbbaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  // ------------------------------------------------------------ wetlands
  frog: {
    palette: { o: OUT, a: GRN, b: LIM, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '.oooo......oooo.',
      '.owko......okwo.',
      '.owwooooooowwoo.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaakaakaaaao.',
      '.oakkkkkkkkkkao.',
      '.oaaaaaaaaaaaao.',
      '.oabbbbbbbbbbao.',
      '.oabbbbbbbbbbao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  turtle: {
    palette: { o: OUT, a: GRN, b: BRD, c: TAN, k: INK, w: WHT },
    rows: [
      EMPTY,
      '...oooooooooo...',
      '..obbbbbbbbbbo..',
      '.obbcbbccbbcbbo.',
      '.obbbbbbbbbbbbo.',
      '.oobbbbbbbbbboo.',
      '..oaaaaaaaaaao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oaaaaaaaaaao..',
      '..oaaakaakaaao..',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  gecko: {
    palette: { o: OUT, a: LIM, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      EMPTY,
      '..oooooooooooo..',
      '.oaaaaaaaaaaaao.',
      'owkoaaaaaaaaokwo',
      'oooaaaaaaaaaaooo',
      '.oaaaaaaaaaaaao.',
      '.oaakaaaaaakaao.',
      '.oaakkkkkkkkaao.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  // ---------------------------------------------------------------- sea
  octopus: {
    palette: { o: OUT, a: PRP, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '....oooooooo....',
      '..ooaaaaaaaaoo..',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaakkaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oaoaaoaaoaaoao.',
      '.oaoaao..oaaoao.',
      '.oo.oo....oo.oo.',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  squid: {
    palette: { o: OUT, a: PKD, k: INK, w: WHT },
    rows: [
      '.......oo.......',
      '......oaao......',
      '.....oaaaao.....',
      '....oaaaaaao....',
      '...oaaaaaaaao...',
      '...oaaaaaaaao...',
      '...oakkaakkao...',
      '...oakwaakwao...',
      '...oaaaaaaaao...',
      '...oaooaaooao...',
      '...oao.oo.oao...',
      '....oo.oo.oo....',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  shrimp: {
    palette: { o: OUT, a: PNK, b: PKD, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      EMPTY,
      '....oooooooo....',
      '..ooaaaaaaaaoo..',
      '.oaaoaaoaaoaaao.',
      '.okaaoaaoaaoaao.',
      '.oaaaoaaoaaobbo.',
      '..oo.oaaoaaobbo.',
      '.....oaaaaaobbo.',
      '......ooooooboo.',
      '.........obbbo..',
      '..........ooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  crab: {
    palette: { o: OUT, a: RED, k: INK, w: WHT },
    rows: [
      EMPTY,
      '..oo........oo..',
      '.oaao......oaao.',
      '.oaao......oaao.',
      '..oao......oao..',
      '...oooooooooo...',
      '..oaaaaaaaaaao..',
      '.oaakwaaaawkaao.',
      '.oaakkaaaakkaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaawawawaaaao.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      '.o.o.o....o.o.o.',
      EMPTY,
      EMPTY,
    ],
  },
  lobster: {
    palette: { o: OUT, a: RED, b: '#b23c30', k: INK, w: WHT },
    rows: [
      '.ooo........ooo.',
      'oaaao......oaaao',
      'oaaaao....oaaaao',
      'oaaoao....oaoaao',
      '.oo.oo....oo.oo.',
      '....oooooooo....',
      '...oakaaaakao...',
      '...oaaaaaaaao...',
      '...oaaaaaaaao...',
      '...obbaaaabbo...',
      '...oaaaaaaaao...',
      '...obbaaaabbo...',
      '...oaaaaaaaao...',
      '....oobbbboo....',
      '...obbbbbbbbo...',
      '....oooooooo....',
    ],
  },
  pufferfish: {
    palette: { o: OUT, a: SND, b: YLW, k: INK, w: WHT },
    rows: [
      '...o...oo...o...',
      '..oooooooooooo..',
      '.obbbbbbbbbbbbo.',
      'o.obbbbbbbbbbo.o',
      '.obbbbbbbbbbbbo.',
      '.obwkwbbbbwkwbo.',
      'o.bwkwbbbbwkwb.o',
      '.obbbbbaabbbbbo.',
      '.obbbbbaabbbbbo.',
      'o.obbbbbbbbbbo.o',
      '.oabbbbbbbbbbao.',
      '..oooooooooooo..',
      '...o...oo...o...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  fish: {
    palette: { o: OUT, a: ORG, b: YLW, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      EMPTY,
      '.o...ooooooo....',
      '.oo.oaabaaaao...',
      '.oooaaabaaaakwo.',
      '.oooaaabaaaaako.',
      '.oo.oaabaaaao...',
      '.o...ooooooo....',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  dolphin: {
    palette: { o: OUT, a: GRY, b: GRL, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      EMPTY,
      '......oo........',
      '.....oaao.......',
      '..oooaaaaooo....',
      '.oaaaaaaaaaaoo..',
      'oboakwaaaaaaaao.',
      'oobaaaaaaaaaaoo.',
      '.oaabbbbbbaao.o.',
      '..oooooooooo..o.',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  whale: {
    palette: { o: OUT, a: BLU, b: GRL, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '....w..w........',
      '.....ww.........',
      '...oooooooo.....',
      '..oaaaaaaaaoo...',
      '.oaaaaaaaaaaaoo.',
      '.oakwaaaaaaaaao.',
      '.oaaaaaaaaaaoo..',
      '.obbbbbbbbaao.o.',
      '..oooooooooo..o.',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  shark: {
    palette: { o: OUT, a: GRD, b: WHT, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '......oo........',
      '.....oaao.......',
      '..oooaaaaooo....',
      '.oaaaaaaaaaaoo..',
      'oaakwaaaaaaaaao.',
      'oaaaaaaaaaaaaoo.',
      '.obwbwbwbaaao.o.',
      '..obbbbbbaao..o.',
      '...oooooooo.....',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  seal: {
    palette: { o: OUT, a: GRY, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '...oooooooooo...',
      '..oaaaaaaaaaao..',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaawwaaaawwaao.',
      '.oaawwakkawwaao.',
      '.oakwwaaaawwkao.',
      '.oaaaaaaaaaaaao.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  otter: {
    palette: { o: OUT, a: BRN, b: CRM, k: INK, w: WHT },
    rows: [
      EMPTY,
      '..oo........oo..',
      '.oaao......oaao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaabbbbbbbbaao.',
      '.oaabbbkkbbbaao.',
      '.oaabbbbbbbbaao.',
      '.oaabwwwwwwbaao.',
      '.oaaabbbbbbaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  // --------------------------------------------------------------- birds
  penguin: {
    palette: { o: OUT, a: BLK, y: ORG, c: ORG, k: INK, w: WHT },
    rows: [
      EMPTY,
      '....oooooooo....',
      '..ooaaaaaaaaoo..',
      '.oaaaaaaaaaaaao.',
      '.oaawwwwwwwwaao.',
      '.oawwkwwwwkwwao.',
      '.oawwwwyywwwwao.',
      '.oaawwyyyywwaao.',
      '.oaawwwwwwwwaao.',
      '.oaawwwwwwwwaao.',
      '.oaawwwwwwwwaao.',
      '.oaawwwwwwwwaao.',
      '.ocaawwwwwwaaco.',
      '..oooooooooooo..',
      EMPTY,
      EMPTY,
    ],
  },
  duck: {
    palette: { o: OUT, a: YLW, y: ORG, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '....oooooooo....',
      '..ooaaaaaaaaoo..',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oaayyyyyyyyaao.',
      '.oaayyyyyyyyaao.',
      '.oaaayyyyyyaaao.',
      '.oaaaaaaaaaaaao.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  swan: {
    palette: { o: OUT, a: WHT, y: ORG, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '.....oooo.......',
      '....oaaaao......',
      '....oakmaoyyo...',
      '....oaammyyyo...',
      '.....oaao.......',
      '.....oaao.......',
      '.....oaao.......',
      '....oaaao.......',
      '..ooaaaaoo......',
      '.oaaaaaaaaoo....',
      '.oaaaaaaaaaaoo..',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  eagle: {
    palette: { o: OUT, a: WHT, b: BRD, y: GLD, k: INK, w: WHT },
    rows: [
      EMPTY,
      '....oooooooo....',
      '..ooaaaaaaaaoo..',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakaaaaaaaakao.',
      '.oaaaaayyaaaaao.',
      '.oaaaayyyyaaaao.',
      '.oaaaaayyaaaaao.',
      '.obbaaaaaaaabbo.',
      '.obbbbaaaabbbbo.',
      '.obbbbbbbbbbbbo.',
      '.obbbbbbbbbbbbo.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  parrot: {
    palette: { o: OUT, a: RED, b: WHT, c: GND, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '....oooooooo....',
      '..ooaaaaaaaaoo..',
      '.oaaaaaaaaaaaao.',
      '.oaabbaaaabbaao.',
      '.oaabkaaaakbaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaammmmaaaao.',
      '.oaaaaammmaaaao.',
      '.oaaaaaammaaaao.',
      '.occaaaaaaaacco.',
      '.occccaaaacccco.',
      '.occcccccccccco.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  flamingo: {
    palette: { o: OUT, a: PNK, b: PKD, m: BLK, k: INK, w: WHT },
    rows: [
      '.....ooooo......',
      '....oaaaaao.....',
      '....oakwaao.....',
      '....oaaaammmo...',
      '.....oaao.......',
      '.....oaao.......',
      '.....oaao.......',
      '.....oaao.......',
      '....oaaao.......',
      '..ooaaaaoo......',
      '.obaaaaaaaoo....',
      '.obbaaaaaaaaoo..',
      '..obbaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  peacock: {
    palette: { o: OUT, a: BLU, b: TEA, c: GND, y: GLD, k: INK, w: WHT },
    rows: [
      '..o..o.oo.o..o..',
      '.oboobobboboobo.',
      '.obbobbbbbbobbo.',
      '.obbbbccccbbbbo.',
      '.obbccccccccbbo.',
      '.obccooooooccbo.',
      '.obcoaaaaaaocbo.',
      '.obcoakaakaocbo.',
      '.obcoawaawaocbo.',
      '.obcoaaaaaaocbo.',
      '.obcoaayyaaocbo.',
      '.oboaaaaaaaaobo.',
      '..ooaaaaaaaaoo..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  rooster: {
    palette: { o: OUT, a: WHT, r: RED, y: GLD, k: INK, w: WHT },
    rows: [
      '......orro......',
      '....oorrrroo....',
      '....orrrrrro....',
      '..ooaaaaaaaaoo..',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaayyaaaaao.',
      '.oaaaayyyyaaaao.',
      '.oaaaaarraaaaao.',
      '.oaaaaarraaaaao.',
      '.oaaaaaaaaaaaao.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  chick: {
    palette: { o: OUT, a: YLW, y: ORG, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '.......o........',
      '....oooaoooo....',
      '..ooaaaaaaaaoo..',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaayyaaaaao.',
      '.oaaaayyyyaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '..oaaaaaaaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  // ---------------------------------------------------------------- bugs
  butterfly: {
    palette: { o: OUT, a: PRP, b: PNK, k: INK, w: WHT },
    rows: [
      '..o..........o..',
      '...o........o...',
      '.oooo..oo..oooo.',
      '.oaaaaokkoaaaao.',
      '.oabbaokkoabbao.',
      '.oabbaokkoabbao.',
      '.oaaaaokkoaaaao.',
      '..oaaaokkoaaao..',
      '.oaaaaokkoaaaao.',
      '.oabbaokkoabbao.',
      '.oabbaokkoabbao.',
      '..oaaaokkoaaao..',
      '...oo.okko.oo...',
      '.......oo.......',
      EMPTY,
      EMPTY,
    ],
  },
  bee: {
    palette: { o: OUT, a: YLW, m: BLK, k: INK, w: WHT },
    rows: [
      '...o........o...',
      '...o........o...',
      '....oooooooo....',
      '...oaaaaaaaao...',
      '..oaakaaaakaao..',
      '..oaakwaawkaao..',
      '...oaaaaaaaao...',
      'w..ommmmmmmmo..w',
      'ww.oaaaaaaaao.ww',
      'ww.ommmmmmmmo.ww',
      'w..oaaaaaaaao..w',
      '...ommmmmmmmo...',
      '....oooooooo....',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  ladybug: {
    palette: { o: OUT, a: RED, m: BLK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '...o........o...',
      '....o......o....',
      '....ommmmmmo....',
      '...omwmmmmwmo...',
      '..oaaaaooaaaao..',
      '.oakaaaooaaakao.',
      '.oaaaaaooaaaaao.',
      '.oaaakaooakaaao.',
      '.oaaaaaooaaaaao.',
      '.oakaaaooaaakao.',
      '..oaaaaooaaaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  snail: {
    palette: { o: OUT, a: SND, b: BRN, c: TAN, k: INK, w: WHT },
    rows: [
      EMPTY,
      '.o..o...........',
      '.o..o.oooooo....',
      '..oo.obbbbbbo...',
      '..oaobbccccbbo..',
      '.oaaobccbbccbo..',
      '.okaobccbbccbo..',
      '.oaaobccccccbo..',
      '.oaaoobbbbbboo..',
      '.oaaaobbbbbbo...',
      '.oaaaaoooooo....',
      '.oaaaaaaaaaaoo..',
      '..oooooooooooo..',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  // -------------------------------------------------------------- mythic
  unicorn: {
    palette: { o: OUT, a: WHT, b: PNK, y: GLD, p: PRP, k: INK, w: WHT },
    rows: [
      '.......oyo......',
      '.......oyo......',
      '...oo..oyo.oo...',
      '..oaao.oyooaao..',
      '..oaapooooopao..',
      '..oaappaaappao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oappaaaaapao..',
      '..oapaaaaaaapo..',
      '..oabbbbbbbbao..',
      '..oabkbbbbkbao..',
      '..oabbbbbbbbao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  dragon: {
    palette: { o: OUT, a: GND, b: LIM, c: CRM, k: INK, w: WHT },
    rows: [
      '..o..........o..',
      '.oco........oco.',
      '.occo......occo.',
      '.oaaoooooooaaoo.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.obbaaaaaaaabbo.',
      '.obbakaaaakabbo.',
      '.obwbwbwbwbwbbo.',
      '.obbbbbbbbbbbbo.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  // ------------------------------------------------------------- hoofed
  horse: {
    palette: { o: OUT, a: BRN, b: TAN, m: BRD, k: INK, w: WHT },
    rows: [
      '...oo..m...oo...',
      '..oaao.mm.oaao..',
      '..oaaoommooaao..',
      '..oaammmaaaaao..',
      '..oaammaaaaaao..',
      '..oakmaaaakkao..',
      '..oakmwaaakwao..',
      '..oaamaaaaaaao..',
      '..oaaaaaaaaaao..',
      '..oabbbbbbbbao..',
      '..oabkbbbbkbao..',
      '..oabbbbbbbbao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  zebra: {
    palette: { o: OUT, a: WHT, b: BLK, m: BLK, k: INK, w: WHT },
    rows: [
      '...oo......oo...',
      '..oaao....oaao..',
      '..oaaooooooaao..',
      '..oammaaaammao..',
      '..oaaaaaaaaaao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oammaaaammao..',
      '..oaaaaaaaaaao..',
      '..oabbbbbbbbao..',
      '..oabwbbbbwbao..',
      '..oabbbbbbbbao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  giraffe: {
    palette: { o: OUT, a: YLW, b: TAN, c: BRD, k: INK, w: WHT },
    rows: [
      '....oo....oo....',
      '....oco...oco...',
      '..o.oo....oo.o..',
      '..oaao....oaao..',
      '..oaaooooooaao..',
      '..oacaaaaaacao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oaacaaaacaao..',
      '..oaaaaaaaaaao..',
      '..oabbbbbbbbao..',
      '..oabkbbbbkbao..',
      '..oabbbbbbbbao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  elephant: {
    palette: { o: OUT, a: GRY, b: GRL, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '...oo......oo...',
      '.ooaaoooooooaoo.',
      'oaaaoaaaaaaoaaao',
      'oaaoaaaaaaaaoaao',
      'oaaoakkaakkaoaao',
      'oaaoakwaakwaoaao',
      'oaaoaaaaaaaaoaao',
      '.ooaaaobboaaaoo.',
      '..oaaaobboaaao..',
      '...oooobbooo....',
      '......obbo......',
      '.......obbo.....',
      '........ooo.....',
      EMPTY,
    ],
  },
  rhino: {
    palette: { o: OUT, a: GRY, b: GRL, w: WHT, k: INK },
    rows: [
      EMPTY,
      '..oo........oo..',
      '.oaao......oaao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaawwaaaaao.',
      '.oaaaawwwwaaaao.',
      '.obbbaawwaabbbo.',
      '.obbbbaaaabbbbo.',
      '.obkbbbbbbbbkbo.',
      '.obbbbbbbbbbbbo.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  hippo: {
    palette: { o: OUT, a: '#9d8bb0', b: '#c3b4d4', k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '..oo........oo..',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.obbbbbbbbbbbbo.',
      '.obkbbbbbbbbkbo.',
      '.obbbbbbbbbbbbo.',
      '.obbwbbbbbbwbbo.',
      '.obbbbbbbbbbbbo.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  camel: {
    palette: { o: OUT, a: TAN, b: SND, m: BRD, k: INK, w: WHT },
    rows: [
      '...oo......oo...',
      '..oaao....oaao..',
      '..oaaooooooaao..',
      '..oammmmmmmmao..',
      '..oaaaaaaaaaao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oaaaaaaaaaao..',
      '..oaaaaaaaaaao..',
      '..oabbbbbbbbao..',
      '..oabkbbbbkbao..',
      '..oabbbbbbbbao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  llama: {
    palette: { o: OUT, a: CRM, b: WHT, p: PNK, k: INK, w: WHT },
    rows: [
      '..oo........oo..',
      '.oapo......opao.',
      '.oapo......opao.',
      '.oaao......oaao.',
      '..oaaooooooaao..',
      '..oaaaaaaaaaao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oaaaaaaaaaao..',
      '..oaaaaaaaaaao..',
      '..oabbbbbbbbao..',
      '..oabkbbbbkbao..',
      '..oabbbbbbbbao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
    ],
  },
  goat: {
    palette: { o: OUT, a: GRL, b: SND, c: GRD, k: INK, w: WHT },
    rows: [
      '.occ........cco.',
      '..occ......cco..',
      '...oo..oo..oo...',
      '..oaao....oaao..',
      '..oaaooooooaao..',
      '..oaaaaaaaaaao..',
      '..oakkaaaakkao..',
      '..oakwaaaakwao..',
      '..oaaaaaaaaaao..',
      '..oabbbbbbbbao..',
      '..oabkbbbbkbao..',
      '..oabbbbbbbbao..',
      '...ooooaaoooo...',
      '......oaao......',
      '.......oo.......',
      EMPTY,
    ],
  },
  sheep: {
    palette: { o: OUT, a: TAN, b: CRM, p: PNK, k: INK, w: WHT },
    rows: [
      EMPTY,
      '..oooooooooooo..',
      '.obbbbbbbbbbbbo.',
      '.obbbbbbbbbbbbo.',
      '.obboaaaaaaobbo.',
      '.obboaaaaaaobbo.',
      '.obbakkaakkabbo.',
      '.obbakwaakwabbo.',
      '.obboaaaaaaobbo.',
      '.obboaappaaobbo.',
      '.obbboaaaaobbbo.',
      '..obboooooobbo..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  kangaroo: {
    palette: { o: OUT, a: TAN, b: SND, p: PNK, k: INK, w: WHT },
    rows: [
      '..oo........oo..',
      '.oapo......opao.',
      '.oapo......opao.',
      '.oaao......oaao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oaabbbbbbbbaao.',
      '.oaabbbkkbbbaao.',
      '.oaabbbbbbbbaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  // ----------------------------------------------------------- riverbank
  beaver: {
    palette: { o: OUT, a: BRN, b: TAN, k: INK, w: WHT },
    rows: [
      EMPTY,
      '..oo........oo..',
      '.oaao......oaao.',
      '.oaaooooooooaao.',
      '.oaaaaaaaaaaaao.',
      '.oakkaaaaaakkao.',
      '.oakwaaaaaakwao.',
      '.oaaaaaaaaaaaao.',
      '.oaabbbkkbbbaao.',
      '.oaabbbwwbbbaao.',
      '.oaabbbwwbbbaao.',
      '.oaaabbbbbbaaao.',
      '.oaaaaaaaaaaaao.',
      CHIN,
      EMPTY,
      EMPTY,
    ],
  },
  // ------------------------------------------------------------ primates
  monkey: {
    palette: { o: OUT, a: BRN, b: TAN, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '...oooooooooo...',
      '..oaaaaaaaaaao..',
      'ooaabbbbbbbbaaoo',
      'oaoabbbbbbbbaoao',
      'oaoabkbbbbkbaoao',
      'oaoabkwbbwkbaoao',
      'ooaabbbbbbbbaaoo',
      '..oabbbkkbbbao..',
      '..oabbbbbbbbao..',
      '..oaabbbbbbaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  gorilla: {
    palette: { o: OUT, a: BLK, b: GRD, k: INK, w: WHT },
    rows: [
      EMPTY,
      EMPTY,
      '...oooooooooo...',
      '..oaaaaaaaaaao..',
      'ooaaaaaaaaaaaaoo',
      'oaoabbbbbbbbaoao',
      'oaoabkbbbbkbaoao',
      'oaoabkwbbwkbaoao',
      'ooaabbbbbbbbaaoo',
      '..oabbbbbbbbao..',
      '..oabbkbbkbbao..',
      '..oaabbbbbbaao..',
      '...oooooooooo...',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
};
